development:
  adapter: postgresql
  encoding: unicode
  database: quizapp
  host: localhost
  pool: 5
  username: quizapp
  password: test

test:
  adapter: postgresql
  encoding: unicode
  database: quizapp
  host: localhost
  pool: 5
  username: quizapp
  password: test

